# Generated by Django 4.0.3 on 2022-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='books',
            field=models.ManyToManyField(through='books.Library_books', to='books.book'),
        ),
    ]
