# Generated by Django 4.0.3 on 2022-03-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_library_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library_books',
            options={'default_related_name': 'library_books'},
        ),
    ]
