# Generated by Django 4.0.3 on 2022-03-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_library_books_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations_books',
            options={'default_related_name': 'reservations_books'},
        ),
    ]
